In [1]:
from src.utils import Triangle, Vertex
from src.constraints import Simplicial2DConstraint, PDConstraint
from src.solver import ProjectiveDynamicsSolver

import numpy as np

In [2]:
vertices = [
    Vertex(
        position=np.array([1.0, 0.0, 0.0]),
        velocity=np.array([0.0, 0.0, 0.0]),
        mass=1.0,
        external_force=np.array([1.0, 0.0, 0.0]),
    ),
    Vertex(
        position=np.array([3.0, 0.0, 0.0]),
        velocity=np.array([0.0, 0.0, 0.0]),
        mass=1.0,
        external_force=np.array([1.0, 0.0, 0.0]),
    ),
    Vertex(
        position=np.array([1.0, 3.0, 3.0]),
        velocity=np.array([0.0, 0.0, 0.0]),
        mass=1.0,
        external_force=np.array([1.0, 0.0, 0.0]),
    ),
]

triangles = [
    Triangle(0, 1, 2)
]

In [3]:
constraints: list[PDConstraint] = [
    Simplicial2DConstraint(
        triangle=triangles[0],
        intial_positions=np.array([[1.0, 0.0, 0.0], [3.0, 0.0, 0.0], [1.0, 3.0, 3.0]]),
        sigma_min=-1.0,
        sigma_max=1.0,
        weight=1
    )
]

In [4]:
constraints[0].A, constraints[0].S

(array([[ 1,  0, -1],
        [ 0,  1, -1],
        [ 0,  0,  0]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [5]:
solver = ProjectiveDynamicsSolver(
    vertices,
    constraints,
    1
)

In [8]:
solver.perform_step(100)

s=array([[ 1.00000000e+00, -4.44089210e-16, -4.44089210e-16],
       [ 3.00000000e+00,  1.33226763e-15,  1.33226763e-15],
       [ 1.00000000e+00,  3.00000000e+00,  3.00000000e+00]])
rhs=array([[ 1., -3., -3.],
       [ 5., -3., -3.],
       [-1.,  9.,  9.]])
self.global_system_matrix=array([[ 2.,  0., -1.],
       [ 0.,  2., -1.],
       [-1., -1.,  3.]])
[[ 1. -3. -3.]
 [ 5. -3. -3.]
 [-1.  9.  9.]]
rhs=array([[ 1., -3., -3.],
       [ 5., -3., -3.],
       [-1.,  9.,  9.]])
self.global_system_matrix=array([[ 2.,  0., -1.],
       [ 0.,  2., -1.],
       [-1., -1.,  3.]])
[[ 1. -3. -3.]
 [ 5. -3. -3.]
 [-1.  9.  9.]]
rhs=array([[ 1., -3., -3.],
       [ 5., -3., -3.],
       [-1.,  9.,  9.]])
self.global_system_matrix=array([[ 2.,  0., -1.],
       [ 0.,  2., -1.],
       [-1., -1.,  3.]])
[[ 1. -3. -3.]
 [ 5. -3. -3.]
 [-1.  9.  9.]]
rhs=array([[ 1., -3., -3.],
       [ 5., -3., -3.],
       [-1.,  9.,  9.]])
self.global_system_matrix=array([[ 2.,  0., -1.],
       [ 0.,  2., -1.],


In [9]:
np.round(solver.q, 3)

array([[1., 0., 0.],
       [3., 0., 0.],
       [1., 3., 3.]])