In [1]:
from src.utils import Triangle, Vertex
from src.constraints import Simplicial2DConstraint, PDConstraint
from src.solver import ProjectiveDynamicsSolver

import numpy as np
from scipy.spatial.transform import Rotation

In [2]:
vertices = [
    Vertex(
        position=np.array([1.0, 0.0, 0.0]),
        velocity=np.array([0.0, 0.0, 0.0]),
        mass=1.0,
        external_force=np.array([0.0, 0.0, 0.0]),
    ),
    Vertex(
        position=np.array([3.0, 0.0, 0.0]),
        velocity=np.array([0.0, 0.0, 0.0]),
        mass=1.0,
        external_force=np.array([0.0, 0.0, 0.0]),
    ),
    Vertex(
        position=np.array([1.0, 3.0, 3.0]),
        velocity=np.array([0.0, 0.0, 0.0]),
        mass=1.0,
        external_force=np.array([0.0, 0.0, 0.0]),
    ),
]

triangles = [
    Triangle(0, 1, 2)
]

In [3]:
rotation = Rotation.from_euler('x', 90, degrees=True)

constraints: list[PDConstraint] = [
    Simplicial2DConstraint(
        triangle=triangles[0],
        initial_positions=rotation.apply(np.array([[1.0, 0.0, 0.0], [3.0, 0.0, 0.0], [1.0, 3.0, 3.0]])),
        weight=1
    )
]

In [4]:
constraints[0].initial_positions

array([[ 1.,  0.,  0.],
       [ 3.,  0.,  0.],
       [ 1., -3.,  3.]])

In [5]:
constraints[0].A, constraints[0].S

(array([[ 1,  0, -1],
        [ 0,  1, -1],
        [ 1, -1,  0]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [6]:
np.rot90(np.array([[1.0, 0.0, 0.0], [3.0, 0.0, 0.0], [1.0, 3.0, 3.0]])),

(array([[0., 0., 3.],
        [0., 0., 3.],
        [1., 3., 1.]]),)

In [7]:
solver = ProjectiveDynamicsSolver(
    vertices,
    constraints,
    1
)

In [8]:
solver.perform_step(1)

U=array([[-1.00000000e+00, -7.85046229e-17,  1.23259516e-32],
       [ 5.55111512e-17, -7.07106781e-01, -7.07106781e-01],
       [ 5.55111512e-17, -7.07106781e-01,  7.07106781e-01]])
s=array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.09481635e-18]])
V_t=array([[-1.        , -0.        ,  0.        ],
       [-0.        ,  0.70710678, -0.70710678],
       [-0.        , -0.70710678, -0.70710678]])
T=array([[ 1.00000000e+00, -5.55111512e-17,  5.55111512e-17],
       [-5.55111512e-17, -5.00000000e-01,  5.00000000e-01],
       [-5.55111512e-17, -5.00000000e-01,  5.00000000e-01]])
auxiliary_variable=array([[-3.33066907e-16,  2.00000000e+00, -2.00000000e+00],
       [-3.00000000e+00, -3.00000000e+00,  1.11022302e-16],
       [-3.00000000e+00, -3.00000000e+00,  1.11022302e-16]])


In [9]:
3.09481635e-18

3.09481635e-18

In [10]:
vertices = np.array([
    [0, 0, 0],
    [1, 1, 0],
    [0, 0 , 1]
])

In [12]:
l_01 = np.linalg.norm(vertices[1] - vertices[0])
l_12 = np.linalg.norm(vertices[2] - vertices[1])
l_20 = np.linalg.norm(vertices[2] - vertices[0])

In [41]:
mapped_vertices = np.zeros((3, 2))
mapped_vertices[1, 0] = l_01

In [42]:
mapped_vertices[2, 0] = (l_20**2 + l_01**2 - l_12**2) / (2 * l_01)
mapped_vertices[2, 1] = np.sqrt(l_20**2 - mapped_vertices[2, 0]**2)

In [43]:
mapped_vertices

array([[0.00000000e+00, 0.00000000e+00],
       [1.41421356e+00, 0.00000000e+00],
       [3.14018492e-16, 1.00000000e+00]])