In [1]:
from src.utils import Triangle, Vertex
from src.constraints import Simplicial2DConstraint, PDConstraint
from src.solver import ProjectiveDynamicsSolver

import numpy as np

TabError: inconsistent use of tabs and spaces in indentation (solver.py, line 68)

In [ ]:
vertices = [
    Vertex(
        position=np.array([1.0, 0.0, 0.0]),
        velocity=np.array([0.0, 0.0, 0.0]),
        mass=1.0,
        external_force=np.array([0.0, 0.0, 0.0]),
    ),
    Vertex(
        position=np.array([3.0, 0.0, 0.0]),
        velocity=np.array([0.0, 0.0, 0.0]),
        mass=1.0,
        external_force=np.array([0.0, 0.0, 0.0]),
    ),
    Vertex(
        position=np.array([1.0, 3.0, 3.0]),
        velocity=np.array([0.0, 0.0, 0.0]),
        mass=1.0,
        external_force=np.array([0.0, 0.0, 0.0]),
    ),
]

triangles = [
    Triangle(0, 1, 2)
]

In [2]:
constraints: list[PDConstraint] = [
    Simplicial2DConstraint(
        triangle=triangles[0],
        intial_positions=np.array([[1.0, 0.0, 0.0], [3.0, 0.0, 0.0], [1.0, 3.0, 3.0]]),
        sigma_min=-1.0,
        sigma_max=1.0,
        weight=1
    )
]

NameError: name 'triangles' is not defined

In [ ]:
constraints[0].A, constraints[0].S

(array([[ 1,  0, -1],
        [ 0,  1, -1],
        [ 0,  0,  0]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [3]:
solver = ProjectiveDynamicsSolver(
    vertices,
    constraints,
    1
)

NameError: name 'ProjectiveDynamicsSolver' is not defined

In [9]:
solver.perform_step(1)

rhs=array([[ 1., -3., -3.],
       [ 5., -3., -3.],
       [-1.,  9.,  9.]])
self.global_system_matrix=array([[ 2.,  0., -1.],
       [ 0.,  2., -1.],
       [-1., -1.,  3.]])
[[ 1. -3. -3.]
 [ 5. -3. -3.]
 [-1.  9.  9.]]


In [7]:
np.round(solver.q, 3)

array([[1.   , 0.   , 0.   ],
       [3.   , 0.   , 0.   ],
       [1.   , 3.001, 3.001]])