In [3]:
import k3d 
import numpy as np 
import igl 

In [2]:
import os 
import sys
os.system("pwd")

/Users/timurkesdogan/Desktop/simulation/project/bowling-simulation/src


0

In [3]:
v, _, _, f, _, _ = igl.read_obj("../assets/simple_pin.obj")

  o Cube


In [6]:
v + np.array([1,0,0])

array([[ 0.411534, -1.      ,  0.626688],
       [ 0.520772,  1.683213,  0.442368],
       [ 0.417647, -1.      , -0.518943],
       [ 0.576305,  1.677179, -0.280986],
       [ 1.726965, -1.      ,  0.637821],
       [ 1.23411 ,  1.660197,  0.267153],
       [ 1.595002, -1.      , -0.504613],
       [ 1.21051 ,  1.631795, -0.345299]])

In [4]:
plot = k3d.plot()
plot += k3d.mesh(v, f)
plot.display()

/Users/timurkesdogan/miniconda3/envs/foo/lib/python3.7/site-packages/traittypes/traittypes.py:101: UserWarning: Given trait value dtype "float64" does not match required type "float32". A coerced copy has been created.
  np.dtype(self.dtype).name))
/Users/timurkesdogan/miniconda3/envs/foo/lib/python3.7/site-packages/traittypes/traittypes.py:101: UserWarning: Given trait value dtype "int64" does not match required type "uint32". A coerced copy has been created.
  np.dtype(self.dtype).name))


Output()

In [50]:
v = np.array([[0,0,0], [1,0,0], [1,1,0], [0,0,1]], dtype = float)
f = np.array([[0,1,2], [0,2,3], [0,3,1], [1,3,2]], dtype = int  )
q = np.array([[5.0,0,0], [0.2,0.1,0.2]], dtype = float)
P, I, C, N = igl.signed_distance(q, v, f, True)
N

array([[-0.77345908,  0.54691816,  0.32037724],
       [ 0.70710678, -0.70710678,  0.        ]])

In [44]:
j = np.array([1,3,2], dtype = int)
g = np.array([0.5,2,1])
np.sort(g, order=j)

ValueError: Cannot specify order when the array has no fields.

In [ ]:
# S #P list of smallest signed distances
# I #P list of facet indices corresponding to smallest distances
# C #P by 3 list of closest points

In [69]:
import igl
import numpy as np
import polyscope as ps
import k3d
import copy
from utils import Triangle, Object, Collision



object_list = []

# load bowling ball from obj file place in field
v, _, _, f, _, _ = igl.read_obj("../assets/simple_ball.obj")
v = v + np.array([-1, 0, 0])

  o Sphere


In [70]:

object_list.append(Object(v, f))
indices_ball = len(v)


# create global faces and vertices np.arrays
vertices = np.array(v)
faces = np.array(f)

# add pins to the same mesh in this array
v, _, _, f, _, _ = igl.read_obj("../assets/simple_pin.obj")
for i in range(2):
    for j in range(-i, i + 1):
        faces = np.concatenate((faces, f + len(vertices)), axis=0)
        vertices = np.concatenate(
            (vertices, (v + np.array([i * 1.5, 0, 0]) + np.array([0, 0, j * 1.5]))),
            axis=0,
        )
        object_list.append(
            Object(v + np.array([i * 1.5, 0, 0]) + np.array([0, 0, j * 1.5]), f)
        )

# register complete mesh w/ polyscope
ps.init()
mesh = ps.register_surface_mesh("everything", vertices, faces)

# intial all objects as static, except for ball, which is given initial velocity
# slowly approaching pins
initial_velocities = np.zeros(vertices.shape)
initial_velocities[:indices_ball] = np.array([1, 0, 0])

masses = np.ones(len(vertices))
external_forces = np.zeros(vertices.shape)

  o Cube


In [71]:
object_mask = []
vertex_counter = face_counter = 0
object_offsets = []

for object in object_list:
    vertex_mask = np.zeros(len(vertices), dtype=bool)
    face_mask = np.zeros(len(faces), dtype=bool)

    vertex_mask[vertex_counter : vertex_counter + len(object.v)] = True
    face_mask[face_counter : face_counter + len(object.f)] = True
    object_offsets.append((vertex_counter, face_counter))
    vertex_counter += len(object.v)
    face_counter += len(object.f)

    object_mask.append((vertex_mask, face_mask))

In [72]:
i = 0; object = object_list[i]
vertices_i = vertices[~object_mask[i][0]]
faces_i = copy.deepcopy(faces)
faces_i[object_offsets[i][1] :] = faces_i[object_offsets[i][1]:] - len(object.v)
faces_i = faces_i[~object_mask[i][1]]

print(vertices_i.shape, "vs ", vertices.shape)
print(faces_i.shape)

print("min: ", faces_i.min(), "vs ", faces.min())
print("max: ", faces_i.max(), "vs ", faces.max())
print(object.v.shape)

(32, 3) vs  (82, 3)
(48, 3)
min:  0 vs  0
max:  31 vs  81
(50, 3)


In [73]:
plot = k3d.plot()
plot += k3d.mesh(object.v, object.f, color=0xff0000)
plot += k3d.mesh(vertices_i, faces_i, color=0x00ff00)
plot.display()

/home/timur/miniconda3/envs/cloth/lib/python3.8/site-packages/traittypes/traittypes.py:97: UserWarning: Given trait value dtype "float64" does not match required type "float32". A coerced copy has been created.
  warnings.warn(
/home/timur/miniconda3/envs/cloth/lib/python3.8/site-packages/traittypes/traittypes.py:97: UserWarning: Given trait value dtype "int64" does not match required type "uint32". A coerced copy has been created.
  warnings.warn(


Output()

In [96]:
S, I, C, N = igl.signed_distance(object.v, vertices_i, faces_i, True)
collision_mask = S < 0

In [97]:
collision_indices = np.arange(len(object.v))[collision_mask]
C = C[collision_mask]
N = N[collision_mask]
S = S[collision_mask]
I = I[collision_mask]

order = np.argsort(S)

collision_indices = collision_indices[order]
C = C[order]
N = N[order]
I = I[order]

I_mask = I >= object_offsets[i][1]
I[I_mask] = I[I_mask] + object.f.shape[0]

In [98]:
# S #P list of smallest signed distances
# I #P list of facet indices corresponding to smallest distances
# C #P by 3 list of closest points
object_offsets[i][1]
I_mask

array([ True,  True,  True,  True,  True,  True,  True])

In [101]:
collision_indices+ object_offsets[i][0]

array([15, 11, 16, 14, 13, 10,  9])

In [1]:
import torch

In [148]:
list_2 = [torch.tensor([[i, i+1], [i+2, i+3]]).float().to("cpu") for i in range(0,1000,4)]
list_2

[tensor([[0., 1.],
         [2., 3.]]),
 tensor([[4., 5.],
         [6., 7.]]),
 tensor([[ 8.,  9.],
         [10., 11.]]),
 tensor([[12., 13.],
         [14., 15.]]),
 tensor([[16., 17.],
         [18., 19.]]),
 tensor([[20., 21.],
         [22., 23.]]),
 tensor([[24., 25.],
         [26., 27.]]),
 tensor([[28., 29.],
         [30., 31.]]),
 tensor([[32., 33.],
         [34., 35.]]),
 tensor([[36., 37.],
         [38., 39.]]),
 tensor([[40., 41.],
         [42., 43.]]),
 tensor([[44., 45.],
         [46., 47.]]),
 tensor([[48., 49.],
         [50., 51.]]),
 tensor([[52., 53.],
         [54., 55.]]),
 tensor([[56., 57.],
         [58., 59.]]),
 tensor([[60., 61.],
         [62., 63.]]),
 tensor([[64., 65.],
         [66., 67.]]),
 tensor([[68., 69.],
         [70., 71.]]),
 tensor([[72., 73.],
         [74., 75.]]),
 tensor([[76., 77.],
         [78., 79.]]),
 tensor([[80., 81.],
         [82., 83.]]),
 tensor([[84., 85.],
         [86., 87.]]),
 tensor([[88., 89.],
         [90., 91.]

In [149]:
torch.svd(torch.stack([a,b,c,d,e], dim=0))

torch.return_types.svd(
U=tensor([[[-0.4046, -0.9145],
         [-0.9145,  0.4046]],

        [[-0.5921, -0.8059],
         [-0.8059,  0.5921]],

        [[-0.6370, -0.7708],
         [-0.7708,  0.6370]],

        [[-0.6568, -0.7540],
         [-0.7540,  0.6568]],

        [[-0.6679, -0.7442],
         [-0.7442,  0.6679]]]),
S=tensor([[ 5.4650,  0.3660],
        [13.1900,  0.1516],
        [21.1185,  0.0947],
        [29.0860,  0.0688],
        [37.0675,  0.0540]]),
V=tensor([[[-0.5760,  0.8174],
         [-0.8174, -0.5760]],

        [[-0.6521,  0.7581],
         [-0.7581, -0.6521]],

        [[-0.6730,  0.7397],
         [-0.7397, -0.6730]],

        [[-0.6824,  0.7309],
         [-0.7309, -0.6824]],

        [[-0.6878,  0.7259],
         [-0.7259, -0.6878]]]))

In [150]:
u, s, v = torch.svd(b)
s

tensor([13.1900,  0.1516])

In [151]:
bb = torch.block_diag(c, b, a, d, e)

In [152]:
u, s, v = torch.svd(bb) 
s

tensor([37.0675, 29.0860, 21.1185, 13.1900,  5.4650,  0.3660,  0.1516,  0.0947,
         0.0688,  0.0540])

In [153]:
import time

In [156]:
t = time.time()
yy = torch.stack(list_2, dim=0)
for _ in range(1000): 
    u, s, v = torch.svd(yy)
print(time.time() - t)

t = time.time()
for _ in range(1000): 
    for i in list_2:
        u, s, v = torch.svd(i)
print(time.time() - t)

0.22643542289733887
1.5483312606811523


In [159]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

np.linalg.svd(np.stack((a, b), axis=0))

(array([[[-0.21483724,  0.88723069,  0.40824829],
         [-0.52058739,  0.24964395, -0.81649658],
         [-0.82633754, -0.38794278,  0.40824829]],
 
        [[-0.21483724,  0.88723069,  0.40824829],
         [-0.52058739,  0.24964395, -0.81649658],
         [-0.82633754, -0.38794278,  0.40824829]]]),
 array([[1.68481034e+01, 1.06836951e+00, 4.41842475e-16],
        [1.68481034e+01, 1.06836951e+00, 4.41842475e-16]]),
 array([[[-0.47967118, -0.57236779, -0.66506441],
         [-0.77669099, -0.07568647,  0.62531805],
         [-0.40824829,  0.81649658, -0.40824829]],
 
        [[-0.47967118, -0.57236779, -0.66506441],
         [-0.77669099, -0.07568647,  0.62531805],
         [-0.40824829,  0.81649658, -0.40824829]]]))