In [2]:
import numpy as np

### Setup

In [3]:
sigma_min, sigma_max = 0.9, 1.1

In [4]:
initial_positions = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
])

In [5]:
A = np.array(
    [
        [1, 0, 0, -1],
        [0, 1, 0, -1],
        [0, 0, 1, -1],
    ]
)

In [6]:
S = np.zeros((4, 4))
S[0, 0] = 1
S[1, 1] = 1
S[2, 2] = 1
S[3, 3] = 1

In [7]:
X_g = (A @ S @ initial_positions).T
X_g_inv = np.linalg.pinv(X_g)

In [8]:
X_g @ X_g_inv

array([[ 1.00000000e+00,  1.44887383e-16, -1.71672935e-17],
       [-3.13159935e-17,  1.00000000e+00, -2.95935941e-17],
       [ 3.64382901e-16,  0.00000000e+00,  1.00000000e+00]])

### Step

In [9]:
current_positions = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 0.1],
])

In [10]:
X_f = (A @ S @ current_positions).T

In [11]:
U, sigma, V_t = np.linalg.svd(X_f @ X_g_inv)

In [12]:
sigma = np.diag(sigma)

In [378]:
def C(D):
    det_Sigma = np.linalg.det(Sigma + np.diag(D))
    return max(det_Sigma - sigma_max, det_Sigma - sigma_max)

In [21]:
def DC(D):
    det_Sigma = np.repeat(np.linalg.det(sigma + np.diag(D)), 3)
    div = (np.diagonal(sigma) + D)
    return det_Sigma / np.maximum(div, 0.000001)

In [380]:
def D_k(D):
    return (DC(D).T @ D - C(D)) / np.maximum(np.dot(DC(D), DC(D)), 0.00001) * DC(D)

In [16]:
D_k = np.ones(3)

for _ in range(10):
    sigma_p = sigma + np.diag(D_k)
    det_sigma_p = np.linalg.det(sigma_p)
    
    DC_D = np.repeat(det_sigma_p, 3) / np.maximum(np.diagonal(sigma_p), 0.000001)
    C_D = max(det_sigma_p - sigma_min, det_sigma_p - sigma_max)
    
    D_k = (DC_D.T @ D_k - C_D) / np.maximum(np.dot(C_D, C_D), 0.00001) * DC_D

In [23]:
DC(D_k), DC_D

(array([2.2, 2.2, 4. ]), array([2.2, 2.2, 4. ]))

In [18]:
D_0

NameError: name 'D_0' is not defined

In [384]:
SigmaP = Sigma + np.diag(D_0)

In [385]:
SigmaP

array([[1.28273008, 0.        , 0.        ],
       [0.        , 1.2815555 , 0.        ],
       [0.        , 0.        , 0.66859125]])

In [386]:
np.linalg.det(SigmaP)

1.099090339706461